### ISSUE TITLE
[1.20.1]: Crash on startup

### ISSUE THREAD

**Issue by ChromaPIE** [DragonsPlusMinecraft/NethersDelightRefabricated#1]
### Description

Game crashes during loading.

### Mod list

https://mclo.gs/QWQII5c

### Logs

https://mclo.gs/w0v4ZBR
(Only the part where it goes wrong)

### Forge

- [ ] I am using the Forge version of Nether's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by RaymondBlaze** [comment]
I should have test the mod in production environment ;)

Looks like the refmap defined in `nethersdelight.mixins.json` is wrong due to loom's default, I will be fixing this quickly.
