### ISSUE TITLE
[1.20.1]: Strider Slice and Hoglin Hide not dropping

### ISSUE THREAD

**Issue by Etherrrr** [DragonsPlusMinecraft/NethersDelightRefabricated#4]
Strider Slice was shown in the loot table in REI but not dropping
![image](https://github.com/DragonsPlusMinecraft/NethersDelightRefabricated/assets/20717049/2230b9ac-f383-4fab-b16b-f09252409b06)

Hoglin Hide wasn't shown in the loot table. 
![image](https://github.com/DragonsPlusMinecraft/NethersDelightRefabricated/assets/20717049/2ab8f1ea-5f8e-4e5f-b563-d75ab7335dea)

`scavenging_hide_from_hoglin.json` shows that it can be looted when weapons with `hunting_tools` tag was equipped in mainhand.
However there's no weapon tagged with `hunting_tools`.

> ```
> {
>   "type": "farmersdelight:add_item",
>   "conditions": [
>     {
>       "condition": "minecraft:entity_properties",
>       "entity": "killer",
>       "predicate": {
>         "equipment": {
>           "mainhand": {
>             "tag": "nethersdelight:tools/hunting_tools"
>           }
>         }
>       }
>     },
>     {
>       "condition": "minecraft:entity_properties",
>       "entity": "this",
>       "predicate": {
>         "type": "minecraft:hoglin"
>       }
>     }
>   ],
>   "item": "nethersdelight:hoglin_hide"
> }
> ```

Hope for fixing🙁

**Comment by RaymondBlaze** [comment]
Confirmed, the `nethersdelight:tools/hunting_tools` tag was somehow missing during porting. Will be fixed in next release.

**Comment by Etherrrr** [comment]
Nice update! Dropping fix is confirmed.
BTW another small question, is there any plan to fix the `entity loot drop` list? No pressure🙇‍♂️

![image](https://github.com/DragonsPlusMinecraft/NethersDelightRefabricated/assets/20717049/2f7b347c-2db3-44d6-89b0-11b0eb18542e)
