### ISSUE TITLE
[1.20.1]: FireBlockMixin and PistonBaseBlockMixin have @Debug annotation in production jar

### ISSUE THREAD

**Issue by unilock** [DragonsPlusMinecraft/NethersDelightRefabricated#5]
### Description

This mod's FireBlockMixin and PistonBaseBlockMixin classes have the `@Debug` mixin annotation applied, meaning the mixin processor is set to export their target classes every time the game starts. This is not necessary in a production environment. Ideally the annotation can simply be removed.

https://github.com/DragonsPlusMinecraft/NethersDelightRefabricated/blob/ee3eff509cda55901fcbc1dbe2f414f2777f745a/src/main/java/umpaz/nethersdelight/common/mixin/FireBlockMixin.java#L15-L17

https://github.com/DragonsPlusMinecraft/NethersDelightRefabricated/blob/ee3eff509cda55901fcbc1dbe2f414f2777f745a/src/main/java/umpaz/nethersdelight/common/mixin/PistonBaseBlockMixin.java#L17-L19

### Steps to reproduce

1. Install Fabric, Farmer's Delight, Nether's Delight Refabricated, etc.
2. Start the game.
3. `FireBlock` and `PistonBaseBlock` are exported by the mixin processor to `.minecraft/.mixin.out`.

### Mod list

- Fabric API: v0.92.1+1.20.1
- Farmer's Delight Refabricated: v2.1.1
- Nether's Delight Refabricated: v4.1.0

### Logs

N/A

### Forge

- [ ] I am using the Forge version of Nether's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by RaymondBlaze** [comment]
Yep, this is my oversight for not removing these temporary `@Debug` annotations.

I'll release a patch version for this.
