### ISSUE TITLE
[1.20.1]: Furnace can't be crafted

### ISSUE THREAD

**Issue by rtxyd** [DragonsPlusMinecraft/NethersDelightRefabricated#6]
### Description

with this mod, and kubeJS, create a server js file with nothing but
`ServerEvents.recipes(event => {})`
cause furnace not able to be crafted.

### Steps to reproduce

1. create a JS file in directory `kubejs\server_scripts` with content `ServerEvents.recipes(event => {})`
3. enter the game, craft furnace.

### Mod list

architectury 9.2.14
emi 1.1.6+1.20.1+fabric
fabric-api 0.92.1+1.20.1
farmersdelight 1.20.1-2.1.1+refabricated
kubejs 2001.6.5-build.7
NethersDelight-Refabricated-1.20.1-4.1.0
rhino 2001.2.2-build.18

### Logs

[latest.log](https://github.com/DragonsPlusMinecraft/NethersDelightRefabricated/files/15268987/latest.log)

### Forge

- [ ] I am using the Forge version of Nether's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by rtxyd** [comment]
after remove `NethersDelight-Refabricated-1.20.1-4.1.0.jar\data\minecraft\recipes\furnace`, the problem gone.

**Comment by RaymondBlaze** [comment]
What ingredients specifically did you used to craft the furnace? Nether's Delight added blackstone furnace, and thus blackstone can no longer be used to craft vanilla furnace, this is an intended behavior.

I've confirmed that the vanilla furnace is still craftable using cobblestone/cobbled deepslate with Nether's Delight only. Is KubeJS and the script mandatory to reproduce the problem? If so, this should probably go to KubeJS instead, as Nether's Delight is simply using Fabric Recipe API here.

**Comment by rtxyd** [comment]
Just no recipe to furnace, like it's deleted. It seems not an issue with nether's delight to the bottom. 
The case is similar to when json file using the same name, one will cover the other.
I think it's because kubeJS makes       `"fabric:type": "fabric:difference"`  usecase stop working.
yes, I should put this on kubeJS
